# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tutorial',
                'doc_host': 'https://jinoh0731.github.io',
                'git_url': 'https://github.com/jinoh0731/nbdev_tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.core': { 'nbdev_tutorial.core.add': ('core.html#add', 'nbdev_tutorial/core.py'),
                                     'nbdev_tutorial.core.subtract': ('basic.html#subtract', 'nbdev_tutorial/core.py')}}}
