# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['add', 'subtract']

# %% ../nbs/00_core.ipynb 6
def add(x,y):
    return x+y

# %% ../nbs/01_basic.ipynb 4
def subtract(x,y):
    return x-y